"""
sda_questions.py — MCQ dataset for SDA (10 questions per subject across 5 subjects).
Includes theory, concept, and technical code output questions.
"""

SDA_MCQ_DATASET = [
    # --------------------------------------------------------------------------
    # PYTHON (10 questions: 5 syntax_and_core_libraries, 5 oop_and_design_patterns)
    # --------------------------------------------------------------------------
    {
        "question_id": "py_01",
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "difficulty": "basic",
        "question": "What will be the output of `print(type([]) is list)` in Python 3?",
        "option_a": "A. True",
        "option_b": "B. False",
        "option_c": "C. TypeError",
        "option_d": "D. <class 'list'>",
        "correct_option": "A. True",
        "explanation": "`[]` creates a list instance whose type is `list`. The `is` identity comparison yields `True`."
    },
    {
        "question_id": "py_02",
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "difficulty": "basic",
        "question": "Which module in Python standard library provides support for high-performance container datatypes like `deque` and `Counter`?",
        "option_a": "A. itertools",
        "option_b": "B. collections",
        "option_c": "C. functools",
        "option_d": "D. datatypes",
        "correct_option": "B. collections",
        "explanation": "The `collections` module implements specialized container datatypes providing alternatives to Python's general purpose built-ins."
    },
    {
        "question_id": "py_03",
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "What is the result of evaluating `[x**2 for x in range(5) if x % 2 == 0]`?",
        "option_a": "A. [0, 1, 4, 9, 16]",
        "option_b": "B. [0, 4, 16]",
        "option_c": "C. [1, 9]",
        "option_d": "D. [4, 16]",
        "correct_option": "B. [0, 4, 16]",
        "explanation": "`range(5)` generates 0, 1, 2, 3, 4. Even numbers are 0, 2, 4. Squaring them produces [0, 4, 16]."
    },
    {
        "question_id": "py_04",
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "What is the primary difference between a list comprehension and a generator expression in Python?",
        "option_a": "A. Generator expressions return tuples instead of lists",
        "option_b": "B. Generator expressions evaluate elements lazily on demand using memory efficiently",
        "option_c": "C. List comprehensions are slower than generator expressions",
        "option_d": "D. Generator expressions cannot take `if` conditions",
        "correct_option": "B. Generator expressions evaluate elements lazily on demand using memory efficiently",
        "explanation": "Generator expressions (in parentheses) yield items one by one using lazy evaluation, saving memory for large sequences."
    },
    {
        "question_id": "py_05",
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "difficulty": "advanced",
        "question": "What is the output of the following code snippet?\n\n```python\na = [1, 2, 3]\nb = a\nb += [4, 5]\nprint(len(a))\n```",
        "option_a": "A. 3",
        "option_b": "B. 5",
        "option_c": "C. 2",
        "option_d": "D. TypeError",
        "correct_option": "B. 5",
        "explanation": "In-place addition (`+=`) on mutable objects like lists mutates the original list in-place. Since `a` and `b` reference the same object, `len(a)` is 5."
    },
    {
        "question_id": "py_06",
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "difficulty": "basic",
        "question": "Which built-in Python function or attribute inspects the Method Resolution Order (MRO) of a class?",
        "option_a": "A. Class.__mro__ or Class.mro()",
        "option_b": "B. Class.__hierarchy__",
        "option_c": "C. inspect.getmro() only",
        "option_d": "D. Class.__parents__",
        "correct_option": "A. Class.__mro__ or Class.mro()",
        "explanation": "Python classes provide the `__mro__` attribute or `mro()` method to display the C3 linearization order for attribute lookup."
    },
    {
        "question_id": "py_07",
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "Which of the following describes how Python handles multiple inheritance when resolving method calls using `super()`?",
        "option_a": "A. Calls the immediate left parent class only",
        "option_b": "B. Follows the C3 Linearization algorithm to determine method resolution order",
        "option_c": "C. Raises an AmbiguityError if two parents share a method name",
        "option_d": "D. Resolves methods depth-first from left to right ignoring order",
        "correct_option": "B. Follows the C3 Linearization algorithm to determine method resolution order",
        "explanation": "Python uses the C3 Linearization algorithm to construct a deterministic Method Resolution Order (MRO) for multiple inheritance."
    },
    {
        "question_id": "py_08",
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "What will be the output of the following Python OOP code?\n\n```python\nclass A:\n    def show(self):\n        print('A')\n\nclass B(A):\n    def show(self):\n        print('B')\n\nobj = B()\nobj.show()\n```",
        "option_a": "A. A",
        "option_b": "B. B",
        "option_c": "C. A B",
        "option_d": "D. Error",
        "correct_option": "B. B",
        "explanation": "Class `B` overrides the `show()` method of class `A`. Calling `obj.show()` on an instance of `B` executes `B.show()`, printing 'B'."
    },
    {
        "question_id": "py_09",
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "In Python design patterns, how can a Singleton pattern be implemented natively using module mechanics?",
        "option_a": "A. Python modules are singletons by default because imports are cached in `sys.modules`",
        "option_b": "B. By declaring all class methods with `@classmethod`",
        "option_c": "C. By inheriting from `abc.ABC`",
        "option_d": "D. Using `@staticmethod` inside an `__init__.py` file",
        "correct_option": "A. Python modules are singletons by default because imports are cached in `sys.modules`",
        "explanation": "Python imports run code only once per process and cache the resulting module object in `sys.modules`, making module-level declarations an idiomatic Singleton."
    },
    {
        "question_id": "py_10",
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "What is the main purpose of Python's `@property` decorator in class design?",
        "option_a": "A. To convert a method into a static method",
        "option_b": "B. To allow getter, setter, and deleter methods to be accessed like attributes while preserving encapsulation",
        "option_c": "C. To automatically make all class attributes private",
        "option_d": "D. To enforce type annotations on method parameters",
        "correct_option": "B. To allow getter, setter, and deleter methods to be accessed like attributes while preserving encapsulation",
        "explanation": "The `@property` decorator creates managed attributes, enabling custom validation and computation on attribute access without breaking public API syntax."
    },

    # --------------------------------------------------------------------------
    # JAVA (10 questions: 5 syntax_and_collections, 5 oop_and_jvm_concepts)
    # --------------------------------------------------------------------------
    {
        "question_id": "java_01",
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "difficulty": "basic",
        "question": "Which Java Collections Framework interface does `HashMap` implement?",
        "option_a": "A. Collection",
        "option_b": "B. List",
        "option_c": "C. Map",
        "option_d": "D. Set",
        "correct_option": "C. Map",
        "explanation": "`HashMap` implements `java.util.Map`, which is separate from the `java.util.Collection` interface hierarchy."
    },
    {
        "question_id": "java_02",
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "difficulty": "basic",
        "question": "What is the time complexity of element lookup by key in a well-balanced `HashMap` in Java 8+?",
        "option_a": "A. O(N)",
        "option_b": "B. O(1) average, O(log N) worst case for hash collisions (balanced trees)",
        "option_c": "C. O(N log N)",
        "option_d": "D. O(N^2)",
        "correct_option": "B. O(1) average, O(log N) worst case for hash collisions (balanced trees)",
        "explanation": "Java 8 converted bucket linked lists to red-black trees when collision thresholds are reached, improving worst-case lookup from O(N) to O(log N)."
    },
    {
        "question_id": "java_03",
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "What will be the output of the following Java snippet?\n\n```java\nString s1 = \"hello\";\nString s2 = new String(\"hello\");\nSystem.out.println((s1 == s2) + \" \" + s1.equals(s2));\n```",
        "option_a": "A. true true",
        "option_b": "B. false true",
        "option_c": "C. false false",
        "option_d": "D. true false",
        "correct_option": "B. false true",
        "explanation": "`s1 == s2` compares object references (false because `new String()` creates a new heap instance), while `equals()` compares character contents (true)."
    },
    {
        "question_id": "java_04",
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "Which interface should a Java class implement to enable custom sorting using `Collections.sort(list)` without passing an external comparator?",
        "option_a": "A. java.lang.Comparable",
        "option_b": "B. java.util.Comparator",
        "option_c": "C. java.util.Sortable",
        "option_d": "D. java.lang.Cloneable",
        "correct_option": "A. java.lang.Comparable",
        "explanation": "Implementing `Comparable<T>` requires defining `compareTo(T o)`, providing the natural ordering for instances of that class."
    },
    {
        "question_id": "java_05",
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "difficulty": "advanced",
        "question": "What is the key functional difference between `ArrayList` and `LinkedList` in Java for element insertion at index 0?",
        "option_a": "A. ArrayList is O(1) while LinkedList is O(N)",
        "option_b": "B. LinkedList is O(1) node pointer update while ArrayList requires O(N) array element shifting",
        "option_c": "C. Both are O(1) in all circumstances",
        "option_d": "D. ArrayList throws IndexOutOfBoundsException if inserted at index 0",
        "correct_option": "B. LinkedList is O(1) node pointer update while ArrayList requires O(N) array element shifting",
        "explanation": "Inserting at index 0 in an `ArrayList` shifts all existing elements one spot right O(N). `LinkedList` updates head pointers in O(1)."
    },
    {
        "question_id": "java_06",
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "difficulty": "basic",
        "question": "Which JVM memory region stores class structures, method data, and field descriptors in Java 8 and later?",
        "option_a": "A. PermGen",
        "option_b": "B. Metaspace",
        "option_c": "C. Java Heap",
        "option_d": "D. Native Stack",
        "correct_option": "B. Metaspace",
        "explanation": "Java 8 replaced Permanent Generation (PermGen) with Metaspace, which allocates class metadata in native memory."
    },
    {
        "question_id": "java_07",
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "What happens when a method is declared with the `final` keyword in a Java class?",
        "option_a": "A. The method cannot be overloaded",
        "option_b": "B. The method cannot be overridden by subclasses",
        "option_c": "C. The method can only be invoked statically",
        "option_d": "D. The method automatically executes on a background thread",
        "correct_option": "B. The method cannot be overridden by subclasses",
        "explanation": "Marking a method `final` prevents subclasses from overriding its implementation, allowing compiler optimizations like inline expansion."
    },
    {
        "question_id": "java_08",
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "What will be printed when executing this Java program?\n\n```java\nclass Parent {\n    static void greet() { System.out.print(\"Parent \"); }\n}\nclass Child extends Parent {\n    static void greet() { System.out.print(\"Child \"); }\n}\npublic class Test {\n    public static void main(String[] args) {\n        Parent obj = new Child();\n        obj.greet();\n    }\n}\n```",
        "option_a": "A. Child ",
        "option_b": "B. Parent ",
        "option_c": "C. Parent Child ",
        "option_d": "D. Compilation Error",
        "correct_option": "B. Parent ",
        "explanation": "Static methods in Java are not overridden dynamically; they are hidden and bound at compile time based on the declared reference type (`Parent`)."
    },
    {
        "question_id": "java_09",
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "How does the JVM Garbage Collector identify unreachable objects when using Garbage-First (G1) GC?",
        "option_a": "A. Reference counting on every assignment",
        "option_b": "B. Root set reachability analysis (tracing objects reachable from Thread stacks, static fields, and JNI handles)",
        "option_c": "C. Destructor callbacks",
        "option_d": "D. Periodic heap snapshot hashing",
        "correct_option": "B. Root set reachability analysis (tracing objects reachable from Thread stacks, static fields, and JNI handles)",
        "explanation": "Modern JVM GCs perform reachability analysis starting from GC Roots (stack frames, static references, JNI pointers) to mark live objects."
    },
    {
        "question_id": "java_10",
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "What is the fundamental difference between an Abstract Class and an Interface in Java 17?",
        "option_a": "A. Interfaces cannot have default or static methods",
        "option_b": "B. Abstract classes can maintain instance state (field variables), whereas interfaces cannot store non-final instance fields",
        "option_c": "C. Classes can extend multiple abstract classes but implement only one interface",
        "option_d": "D. Abstract classes cannot have constructors",
        "correct_option": "B. Abstract classes can maintain instance state (field variables), whereas interfaces cannot store non-final instance fields",
        "explanation": "Interfaces can define behavior (including `default` methods since Java 8), but cannot hold instance state (fields in interfaces are implicitly `public static final`)."
    },

    # --------------------------------------------------------------------------
    # DBMS (10 questions: 5 sql_queries_and_joins, 5 normalization_and_transactions)
    # --------------------------------------------------------------------------
    {
        "question_id": "db_01",
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "difficulty": "basic",
        "question": "Which SQL JOIN clause returns all records from the left table and matched records from the right table, filling missing right values with NULL?",
        "option_a": "A. INNER JOIN",
        "option_b": "B. LEFT OUTER JOIN",
        "option_c": "C. RIGHT OUTER JOIN",
        "option_d": "D. FULL OUTER JOIN",
        "correct_option": "B. LEFT OUTER JOIN",
        "explanation": "`LEFT JOIN` (or `LEFT OUTER JOIN`) preserves all rows from the left table regardless of whether a matching row exists on the right."
    },
    {
        "question_id": "db_02",
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "difficulty": "basic",
        "question": "In SQL, which clause filters aggregate results generated by a `GROUP BY` statement?",
        "option_a": "A. WHERE",
        "option_b": "B. HAVING",
        "option_c": "C. ORDER BY",
        "option_d": "D. FILTER",
        "correct_option": "B. HAVING",
        "explanation": "`WHERE` filters rows before aggregation; `HAVING` filters aggregated groups after `GROUP BY` is applied."
    },
    {
        "question_id": "db_03",
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "What is the output of the following SQL query if `Employees` has 10 rows and `Departments` has 5 rows?\n\n```sql\nSELECT * FROM Employees CROSS JOIN Departments;\n```",
        "option_a": "A. 10 rows",
        "option_b": "B. 15 rows",
        "option_c": "C. 50 rows",
        "option_d": "D. 5 rows",
        "correct_option": "C. 50 rows",
        "explanation": "A `CROSS JOIN` produces a Cartesian product multiplying the row counts of both tables (10 × 5 = 50)."
    },
    {
        "question_id": "db_04",
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "Which SQL Window function assigns a unique sequential integer to rows within a partition starting at 1 without gaps?",
        "option_a": "A. RANK()",
        "option_b": "B. DENSE_RANK()",
        "option_c": "C. ROW_NUMBER()",
        "option_d": "D. NTILE()",
        "correct_option": "C. ROW_NUMBER()",
        "explanation": "`ROW_NUMBER()` assigns strict sequential integers (1, 2, 3...) to every row within a partition regardless of duplicate values."
    },
    {
        "question_id": "db_05",
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "difficulty": "advanced",
        "question": "How does a `LEFT JOIN` differ from an `EXISTS` subquery when retrieving parent rows with matching children in SQL?",
        "option_a": "A. LEFT JOIN duplicates parent rows when multiple child matches exist, whereas EXISTS returns each parent row at most once",
        "option_b": "B. EXISTS cannot be used with WHERE clauses",
        "option_c": "C. LEFT JOIN never uses indexes",
        "option_d": "D. EXISTS always performs a full table scan",
        "correct_option": "A. LEFT JOIN duplicates parent rows when multiple child matches exist, whereas EXISTS returns each parent row at most once",
        "explanation": "Joining a 1-to-many child table via `LEFT JOIN` expands parent rows for every child match, while `EXISTS` short-circuits on the first match."
    },
    {
        "question_id": "db_06",
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "difficulty": "basic",
        "question": "What does the 'A' stand for in the ACID properties of database transactions?",
        "option_a": "A. Availability",
        "option_b": "B. Atomicity",
        "option_c": "C. Authentication",
        "option_d": "D. Asynchrony",
        "correct_option": "B. Atomicity",
        "explanation": "Atomicity ensures that all operations within a transaction complete successfully, or the entire transaction is rolled back ('all-or-nothing')."
    },
    {
        "question_id": "db_07",
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "A table is in Third Normal Form (3NF) if it is in 2NF and has no:",
        "option_a": "A. Partial dependencies",
        "option_b": "B. Transitive dependencies",
        "option_c": "C. Multivalued dependencies",
        "option_d": "D. Repeating groups",
        "correct_option": "B. Transitive dependencies",
        "explanation": "3NF requires eliminating transitive functional dependencies (where a non-prime attribute depends on another non-prime attribute)."
    },
    {
        "question_id": "db_08",
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "Which transaction isolation level prevents Dirty Reads but allows Non-Repeatable Reads?",
        "option_a": "A. Read Uncommitted",
        "option_b": "B. Read Committed",
        "option_c": "C. Repeatable Read",
        "option_d": "D. Serializable",
        "correct_option": "B. Read Committed",
        "explanation": "`Read Committed` isolation level guarantees that data read by a query was committed before execution, preventing dirty reads."
    },
    {
        "question_id": "db_09",
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "What concurrency control phenomenon is characterized as a 'Phantom Read'?",
        "option_a": "A. Transaction T1 reads uncommitted changes made by T2",
        "option_b": "B. Transaction T1 re-reads a row and finds modified column values because T2 committed changes",
        "option_c": "C. Transaction T1 executes a range query twice, and receives new matching rows because T2 inserted and committed new records in between",
        "option_d": "D. Two transactions deadlock while requesting shared locks",
        "correct_option": "C. Transaction T1 executes a range query twice, and receives new matching rows because T2 inserted and committed new records in between",
        "explanation": "Phantom reads occur when a transaction re-executes a range search query and finds new rows inserted by another concurrent committed transaction."
    },
    {
        "question_id": "db_10",
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "Why is Boyce-Codd Normal Form (BCNF) strictly stronger than 3NF?",
        "option_a": "A. BCNF permits transitive dependencies if primary keys are composite",
        "option_b": "B. In BCNF, for every functional dependency X -> Y, X MUST be a superkey (no exceptions for prime attributes on the right)",
        "option_c": "C. BCNF requires tables to have at least two candidate keys",
        "option_d": "D. BCNF addresses join dependencies across multiple databases",
        "correct_option": "B. In BCNF, for every functional dependency X -> Y, X MUST be a superkey (no exceptions for prime attributes on the right)",
        "explanation": "3NF allows X -> Y if Y is a prime attribute even if X is not a superkey. BCNF eliminates this exception entirely."
    },

    # --------------------------------------------------------------------------
    # MACHINE LEARNING (10 questions: 5 model_apis_and_libraries, 5 algorithms_and_theory)
    # --------------------------------------------------------------------------
    {
        "question_id": "ml_01",
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "difficulty": "basic",
        "question": "In scikit-learn, which method computes model parameters from training data and transforms the data in a single call?",
        "option_a": "A. fit_predict()",
        "option_b": "B. fit_transform()",
        "option_c": "C. transform_fit()",
        "option_d": "D. train_test_split()",
        "correct_option": "B. fit_transform()",
        "explanation": "`fit_transform()` is available on transformers (like `StandardScaler`) to fit parameters on X and return transformed X efficiently."
    },
    {
        "question_id": "ml_02",
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "difficulty": "basic",
        "question": "Which parameter in scikit-learn's `train_test_split()` ensures class label proportions are preserved across train and test sets?",
        "option_a": "A. shuffle=True",
        "option_b": "B. stratify=y",
        "option_c": "C. random_state=42",
        "option_d": "D. balanced=True",
        "correct_option": "B. stratify=y",
        "explanation": "`stratify=y` performs stratified sampling to maintain the target distribution across splits."
    },
    {
        "question_id": "ml_03",
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "What is the output of the following PyTorch code snippet?\n\n```python\nimport torch\nx = torch.tensor([2.0], requires_grad=True)\ny = x**3 + 5\ny.backward()\nprint(x.grad.item())\n```",
        "option_a": "A. 8.0",
        "option_b": "B. 12.0",
        "option_c": "C. 6.0",
        "option_d": "D. 13.0",
        "correct_option": "B. 12.0",
        "explanation": "The derivative of y = x^3 + 5 is dy/dx = 3*x^2. Evaluating at x = 2.0 gives 3*(2.0^2) = 12.0."
    },
    {
        "question_id": "ml_04",
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "Why must feature scaling (e.g. `StandardScaler`) be fitted ONLY on training data in an ML pipeline?",
        "option_a": "A. To prevent data leakage from the test set into model training parameters",
        "option_b": "B. Because scikit-learn raises an error if test data is fitted",
        "option_c": "C. To make test set predictions faster",
        "option_d": "D. Feature scaling is not necessary for neural networks",
        "correct_option": "A. To prevent data leakage from the test set into model training parameters",
        "explanation": "Fitting scalers on test data introduces data leakage, giving optimistic performance metrics that will fail in production."
    },
    {
        "question_id": "ml_05",
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "difficulty": "advanced",
        "question": "In XGBoost or LightGBM, what is the main advantage of using histogram-based decision tree algorithms?",
        "option_a": "A. Eliminates the need for depth-wise tree growth",
        "option_b": "B. Bins continuous feature values into discrete feature bins, dramatically reducing calculation time for split points",
        "option_c": "C. Replaces loss functions with cross-entropy",
        "option_d": "D. Guaranteed convergence without learning rate tuning",
        "correct_option": "B. Bins continuous feature values into discrete feature bins, dramatically reducing calculation time for split points",
        "explanation": "Histogram binning reduces candidate split points from O(# data points) to O(# bins), drastically cutting memory usage and computation."
    },
    {
        "question_id": "ml_06",
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "difficulty": "basic",
        "question": "Which evaluation metric is defined as True Positives / (True Positives + False Negatives)?",
        "option_a": "A. Precision",
        "option_b": "B. Recall (Sensitivity)",
        "option_c": "C. Specificity",
        "option_d": "D. Accuracy",
        "correct_option": "B. Recall (Sensitivity)",
        "explanation": "Recall measures the proportion of actual positive instances correctly identified by the model."
    },
    {
        "question_id": "ml_07",
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "What problem does L2 Regularization (Ridge) address in Linear Regression?",
        "option_a": "A. Feature selection by driving coefficients to exact zero",
        "option_b": "B. Reduces model variance and prevents overfitting by penalizing large squared coefficient magnitudes",
        "option_c": "C. Fixes non-linear relationships in tabular datasets",
        "option_d": "D. Converts regression into binary classification",
        "correct_option": "B. Reduces model variance and prevents overfitting by penalizing large squared coefficient magnitudes",
        "explanation": "L2 regularization adds a sum of squared weights penalty to the loss function, shrinking weights toward zero and reducing model variance."
    },
    {
        "question_id": "ml_08",
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "What is the core conceptual trade-off described by the Bias-Variance Tradeoff?",
        "option_a": "A. Underfitting due to high bias vs Overfitting due to high variance",
        "option_b": "B. Training speed vs Inference memory footprint",
        "option_c": "C. Supervised vs Unsupervised learning capacity",
        "option_d": "D. Precision vs Recall curve AUC",
        "correct_option": "A. Underfitting due to high bias vs Overfitting due to high variance",
        "explanation": "High bias models make simplistic assumptions (underfitting), while high variance models overfit training noise."
    },
    {
        "question_id": "ml_09",
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "How does Random Forest reduce variance compared to an individual Decision Tree?",
        "option_a": "A. By boosting weak learners sequentially on residual errors",
        "option_b": "B. By bagging (bootstrap aggregating) and random feature subspace sampling to decorrelate individual trees",
        "option_c": "C. By using gradient descent on node splits",
        "option_d": "D. By forcing all trees to share identical root nodes",
        "correct_option": "B. By bagging (bootstrap aggregating) and random feature subspace sampling to decorrelate individual trees",
        "explanation": "Averaging decorrelated trees built on bootstrap samples reduces ensemble variance without increasing bias."
    },
    {
        "question_id": "ml_10",
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "In Transformer architectures (e.g. Attention Is All You Need), what is the time complexity of Self-Attention with respect to sequence length N?",
        "option_a": "A. O(N)",
        "option_b": "B. O(N^2)",
        "option_c": "C. O(N log N)",
        "option_d": "D. O(2^N)",
        "correct_option": "B. O(N^2)",
        "explanation": "Computing pairwise Query-Key dot products across all N tokens results in an N × N attention matrix, giving O(N^2) complexity."
    },

    # --------------------------------------------------------------------------
    # DSA (10 questions: 5 implementation_and_syntax, 5 complexity_and_problem_solving)
    # --------------------------------------------------------------------------
    {
        "question_id": "dsa_01",
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "difficulty": "basic",
        "question": "Which data structure follows the Last-In, First-Out (LIFO) principle?",
        "option_a": "A. Queue",
        "option_b": "B. Stack",
        "option_c": "C. Priority Queue",
        "option_d": "D. Hash Table",
        "correct_option": "B. Stack",
        "explanation": "A Stack operates on a LIFO basis where elements push and pop from the top."
    },
    {
        "question_id": "dsa_02",
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "difficulty": "basic",
        "question": "What is the worst-case space complexity of a Hash Map storing N key-value pairs?",
        "option_a": "A. O(1)",
        "option_b": "B. O(N)",
        "option_c": "C. O(N^2)",
        "option_d": "D. O(log N)",
        "correct_option": "B. O(N)",
        "explanation": "Storing N distinct key-value pairs requires memory proportional to N, giving O(N) space complexity."
    },
    {
        "question_id": "dsa_03",
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "What is the output of the following Python binary search tree traversal snippet on root = [2, 1, 3] in In-Order?\n\n```python\ndef inorder(root):\n    if not root: return []\n    return inorder(root.left) + [root.val] + inorder(root.right)\n```",
        "option_a": "A. [2, 1, 3]",
        "option_b": "B. [1, 2, 3]",
        "option_c": "C. [3, 2, 1]",
        "option_d": "D. [1, 3, 2]",
        "correct_option": "B. [1, 2, 3]",
        "explanation": "In-order traversal visits Left -> Root -> Right, which yields sorted keys [1, 2, 3] for a valid BST."
    },
    {
        "question_id": "dsa_04",
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "difficulty": "intermediate",
        "question": "Which algorithmic technique uses a min-heap or max-heap to efficiently maintain the top K elements from an unsorted stream of size N?",
        "option_a": "A. Binary Search",
        "option_b": "B. Priority Queue (Heap) of size K in O(N log K) time",
        "option_c": "C. Depth First Search",
        "option_d": "D. Dynamic Programming",
        "correct_option": "B. Priority Queue (Heap) of size K in O(N log K) time",
        "explanation": "Maintaining a min-heap of size K requires O(log K) per stream element, processing N elements in O(N log K) total time."
    },
    {
        "question_id": "dsa_05",
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "difficulty": "advanced",
        "question": "What is the code output for detecting cycle start in a Linked List using Floyd's Tortoise and Hare algorithm when fast and slow pointers meet?",
        "option_a": "A. The meeting point is guaranteed to be the cycle head",
        "option_b": "B. Reset one pointer to head and advance both slow and fast pointers 1 step at a time until they meet again at cycle start",
        "option_c": "C. Reverse the linked list pointers",
        "option_d": "D. Clear the next pointers",
        "correct_option": "B. Reset one pointer to head and advance both slow and fast pointers 1 step at a time until they meet again at cycle start",
        "explanation": "Mathematical proof for Floyd's algorithm shows the distance from head to cycle entrance equals the distance from intersection point to cycle entrance."
    },
    {
        "question_id": "dsa_06",
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "difficulty": "basic",
        "question": "What is the average-case time complexity of QuickSort?",
        "option_a": "A. O(N)",
        "option_b": "B. O(N log N)",
        "option_c": "C. O(N^2)",
        "option_d": "D. O(log N)",
        "correct_option": "B. O(N log N)",
        "explanation": "QuickSort divides the array recursively around pivots, averaging O(N log N) time complexity."
    },
    {
        "question_id": "dsa_07",
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "Which graph algorithm finds the shortest path between a single source vertex and all other vertices in a weighted graph with non-negative edge weights?",
        "option_a": "A. Prim's Algorithm",
        "option_b": "B. Dijkstra's Algorithm",
        "option_c": "C. Kruskal's Algorithm",
        "option_d": "D. Topological Sort",
        "correct_option": "B. Dijkstra's Algorithm",
        "explanation": "Dijkstra's algorithm uses a priority queue to iteratively explore minimum distance vertices in non-negative weighted graphs."
    },
    {
        "question_id": "dsa_08",
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "difficulty": "intermediate",
        "question": "What is the worst-case time complexity of searching for an item in an unbalanced Binary Search Tree of N nodes?",
        "option_a": "A. O(1)",
        "option_b": "B. O(log N)",
        "option_c": "C. O(N)",
        "option_d": "D. O(N log N)",
        "correct_option": "C. O(N)",
        "explanation": "An unbalanced BST can degenerate into a single linked list chain, resulting in O(N) traversal depth."
    },
    {
        "question_id": "dsa_09",
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "What key property distinguishes Dynamic Programming from Greedy Algorithms?",
        "option_a": "A. Dynamic programming makes local greedy choices at each step without reconsidering prior decisions",
        "option_b": "B. Dynamic programming evaluates overlapping subproblems and optimal substructure by storing intermediate subproblem solutions",
        "option_c": "C. Greedy algorithms always guarantee global optimal solutions for NP-hard problems",
        "option_d": "D. Dynamic programming can only be implemented iteratively",
        "correct_option": "B. Dynamic programming evaluates overlapping subproblems and optimal substructure by storing intermediate subproblem solutions",
        "explanation": "DP solves problems with overlapping subproblems and optimal substructure via memoization/tabulation, unlike greedy choices which don't look back."
    },
    {
        "question_id": "dsa_10",
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "difficulty": "advanced",
        "question": "What is the tightest upper bound time complexity for the Floyd-Warshall All-Pairs Shortest Path algorithm on a graph with V vertices?",
        "option_a": "A. O(V^2)",
        "option_b": "B. O(V^3)",
        "option_c": "C. O(V * E)",
        "option_d": "D. O(E log V)",
        "correct_option": "B. O(V^3)",
        "explanation": "Floyd-Warshall uses 3 nested loops over all vertices V, resulting in an O(V^3) time complexity."
    }
]

def get_questions_by_subtopic(subject: str, sub_topic: str) -> list[dict]:
    """Retrieve questions matching subject and sub_topic."""
    matches = [
        q for q in SDA_MCQ_DATASET 
        if q["subject"].lower() == subject.lower() and q["sub_topic"].lower() == sub_topic.lower()
    ]
    if not matches:
        # Fallback by subject match
        matches = [q for q in SDA_MCQ_DATASET if q["subject"].lower() == subject.lower()]
    if not matches:
        matches = SDA_MCQ_DATASET[:5]
    return matches
