"""
seed_questions.py — The definitive 50-question question bank from the attached assessment PDF.
Categorized into 5 domains × 2 sub-topics (5 questions each).
"""

QUESTIONS_50 = [
    # =========================================================================
    # SECTION 1: DBMS (Questions 1-10)
    # =========================================================================
    {
        "question_num": 1,
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "question": "Which of the following normal forms deals with transitive functional dependency among non-prime attributes?",
        "option_a": "A) First Normal Form (1NF)",
        "option_b": "B) Second Normal Form (2NF)",
        "option_c": "C) Third Normal Form (3NF)",
        "option_d": "D) Boyce-Codd Normal Form (BCNF)",
        "correct_option": "C",
        "concept_explanation": "3NF removes transitive dependencies (X → Y and Y → Z where Z is non-prime)."
    },
    {
        "question_num": 2,
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "question": "In relational algebra, which operator is equivalent to a Cartesian Product followed by a Selection condition?",
        "option_a": "A) Projection (Π)",
        "option_b": "B) Theta Join (θ-join)",
        "option_c": "C) Natural Join (⨂)",
        "option_d": "D) Division (÷)",
        "correct_option": "B",
        "concept_explanation": "Theta Join is defined as selection σ applied on Cartesian product (R × S)."
    },
    {
        "question_num": 3,
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "question": "Consider a transaction schedule where Transaction T1 reads a data item modified by uncommitted Transaction T2. If T2 fails and aborts, leading to a rollback, what concurrency anomaly has occurred?",
        "option_a": "A) Lost Update",
        "option_b": "B) Non-repeatable Read",
        "option_c": "C) Phantom Read",
        "option_d": "D) Dirty Read",
        "correct_option": "D",
        "concept_explanation": "Reading uncommitted data that later rolls back is a Dirty Read (WR conflict)."
    },
    {
        "question_num": 4,
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "question": "In a B+ Tree of order m, which of the following statements is TRUE regarding leaf nodes?",
        "option_a": "A) Leaf nodes contain only keys, while internal nodes contain keys and actual data records.",
        "option_b": "B) Leaf nodes are linked together as a doubly or singly linked list to allow efficient sequential range traversal.",
        "option_c": "C) Leaf nodes can have a variable depth depending on the number of insertions.",
        "option_d": "D) All data records are stored exclusively in the root and internal index nodes.",
        "correct_option": "B",
        "concept_explanation": "B+ trees store all data/record pointers in linked leaf nodes for rapid range scans."
    },
    {
        "question_num": 5,
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "question": "Consider a relation schema R(A, B, C, D) with functional dependencies: A → B, B → C, and C → D. What is the candidate key of R, and what is the highest normal form that R satisfies?",
        "option_a": "A) Candidate key: {A}; Highest Normal Form: 2NF",
        "option_b": "B) Candidate key: {A}; Highest Normal Form: 3NF",
        "option_c": "C) Candidate key: {A, B}; Highest Normal Form: 1NF",
        "option_d": "D) Candidate key: {D}; Highest Normal Form: BCNF",
        "correct_option": "A",
        "concept_explanation": "Closure A+ = {A,B,C,D}. In 2NF since no partial dependency, but violates 3NF (transitive dependencies exist)."
    },
    {
        "question_num": 6,
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "question": "Consider the following SQL query executed on an Employees table:\n\nSELECT department_id, COUNT(*)\nFROM Employees\nWHERE salary > 50000\nGROUP BY department_id\nHAVING COUNT(*) >= 5;\n\nWhat is the exact logical query processing order of the SQL clauses present?",
        "option_a": "A) FROM → WHERE → GROUP BY → HAVING → SELECT",
        "option_b": "B) SELECT → FROM → WHERE → GROUP BY → HAVING",
        "option_c": "C) FROM → GROUP BY → WHERE → HAVING → SELECT",
        "option_d": "D) FROM → WHERE → SELECT → GROUP BY → HAVING",
        "correct_option": "A",
        "concept_explanation": "Standard ANSI SQL logical evaluation order: FROM → WHERE → GROUP BY → HAVING → SELECT."
    },
    {
        "question_num": 7,
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "question": "Under the Two-Phase Locking (2PL) protocol, what does the 'Strict 2PL' variant mandate to avoid cascading aborts?",
        "option_a": "A) All shared locks must be released before the transaction terminates.",
        "option_b": "B) All exclusive (write) locks obtained by a transaction must be held until the transaction commits or aborts.",
        "option_c": "C) Locks cannot be acquired once a transaction enters the shrinking phase.",
        "option_d": "D) The transaction must pre-declare and acquire all locks simultaneously before beginning execution.",
        "correct_option": "B",
        "concept_explanation": "Strict 2PL retains all exclusive (X) locks until transaction end, ensuring recoverability and avoiding cascading aborts."
    },
    {
        "question_num": 8,
        "subject": "DBMS",
        "sub_topic": "normalization_and_transactions",
        "category": "conceptual",
        "question": "In the ARIES recovery algorithm, what is the primary objective of the Redo phase?",
        "option_a": "A) Rolling back transactions that were active at the time of system crash.",
        "option_b": "B) Reconstructing the Dirty Page Table and Transaction Table using log records since checkpoint.",
        "option_c": "C) Repeating history up to the crash point to restore the database buffer pool to its state before crash.",
        "option_d": "D) Logging compensating log records (CLRs) for aborted operations.",
        "correct_option": "C",
        "concept_explanation": "ARIES Redo repeats history (both committed and uncommitted) to restore buffer pool state to the crash point."
    },
    {
        "question_num": 9,
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "question": "In SQL, what is the key behavioral difference between TRUNCATE TABLE and DELETE FROM table without a WHERE clause?",
        "option_a": "A) TRUNCATE is a DML command and generates undo logs for every row; DELETE is a DDL command.",
        "option_b": "B) TRUNCATE resets high-water marks and identity seeds, deallocates data pages, and cannot fire row-level triggers; DELETE logs row by row and fires delete triggers.",
        "option_c": "C) DELETE automatically drops foreign key constraints, while TRUNCATE preserves indexes.",
        "option_d": "D) TRUNCATE allows conditional filtering with a WHERE clause, while DELETE deletes all rows unconditionally.",
        "correct_option": "B",
        "concept_explanation": "TRUNCATE is DDL that deallocates pages, resets identity counters, and bypasses row triggers; DELETE logs row by row."
    },
    {
        "question_num": 10,
        "subject": "DBMS",
        "sub_topic": "sql_queries_and_joins",
        "category": "procedural",
        "question": "Consider two transactions with schedules:\nT1: R(X), W(X)\nT2: R(X), W(X)\nWhich schedule is conflict serializable?",
        "option_a": "A) R1(X), R2(X), W1(X), W2(X)",
        "option_b": "B) R1(X), W1(X), R2(X), W2(X)",
        "option_c": "C) R1(X), R2(X), W2(X), W1(X)",
        "option_d": "D) R2(X), W1(X), R1(X), W2(X)",
        "correct_option": "B",
        "concept_explanation": "Serial schedule T1 followed by T2; precedence graph contains no cycles."
    },

    # =========================================================================
    # SECTION 2: JAVA PROGRAMMING (Questions 11-20)
    # =========================================================================
    {
        "question_num": 11,
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "question": "Which memory area in the Java Virtual Machine (JVM) is shared among all active threads?",
        "option_a": "A) Java Program Counter (PC) Register",
        "option_b": "B) JVM Stack",
        "option_c": "C) Method Area / Metaspace",
        "option_d": "D) Native Method Stack",
        "correct_option": "C",
        "concept_explanation": "Method Area / Metaspace and Heap are shared across threads; Stacks and PC registers are thread-private."
    },
    {
        "question_num": 12,
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "question": "What will be the output of the following Java snippet?\n\nString s1 = new String(\"Java\");\nString s2 = \"Java\";\nString s3 = s1.intern();\nSystem.out.println((s1 == s2) + \" \" + (s2 == s3));",
        "option_a": "A) true true",
        "option_b": "B) false true",
        "option_c": "C) false false",
        "option_d": "D) true false",
        "correct_option": "B",
        "concept_explanation": "s1 is a new heap object (s1 == s2 is false); s1.intern() returns the string constant pool reference (s2 == s3 is true)."
    },
    {
        "question_num": 13,
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "question": "Which of the following statements regarding the volatile keyword in Java is accurate?",
        "option_a": "A) It guarantees both atomicity and visibility for compound operations like incrementing a variable (i++).",
        "option_b": "B) It prevents instructions from being reordered and ensures visibility across threads, but does not ensure atomicity for compound operations.",
        "option_c": "C) It provides mutual exclusion locking similar to synchronized blocks.",
        "option_d": "D) It forces variable allocation to thread-local stack memory rather than main heap memory.",
        "correct_option": "B",
        "concept_explanation": "volatile enforces happens-before memory visibility & prevents instruction reordering; does not guarantee atomic compound ops."
    },
    {
        "question_num": 14,
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "question": "What will be printed by the following code?\n\nclass Parent {\n  static void display() {\n    System.out.print(\"P \");\n  }\n}\nclass Child extends Parent {\n  static void display() {\n    System.out.print(\"C \");\n  }\n}\npublic class Test {\n  public static void main(String[] args) {\n    Parent obj = new Child();\n    obj.display();\n  }\n}",
        "option_a": "A) C",
        "option_b": "B) P",
        "option_c": "C) Compilation Error: Cannot override static method",
        "option_d": "D) Runtime Exception",
        "correct_option": "B",
        "concept_explanation": "Static methods undergo method hiding, bound at compile time based on reference type (Parent)."
    },
    {
        "question_num": 15,
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "question": "In Java Generics, what does the wildcard expression List<? super Integer> represent?",
        "option_a": "A) A list that can only accept sub-classes of Integer (read-only covariant list).",
        "option_b": "B) A list of an unknown type that is either Integer or a supertype of Integer (contravariant list).",
        "option_c": "C) An immutable list containing exclusively Number and its descendants.",
        "option_d": "D) A compile-time error, as the `super` keyword cannot be used with wildcards.",
        "correct_option": "B",
        "concept_explanation": "Lower bounded wildcard (? super T) denotes contravariance: accepts T or any ancestor/supertype of T."
    },
    {
        "question_num": 16,
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "question": "What is the output of executing the following Java program?\n\npublic class ExceptionDemo {\n  public static int compute() {\n    try {\n      int x = 10 / 0;\n      return 1;\n    } catch (ArithmeticException e) {\n      return 2;\n    } finally {\n      return 3;\n    }\n  }\n  public static void main(String[] args) {\n    System.out.println(compute());\n  }\n}",
        "option_a": "A) 1",
        "option_b": "B) 2",
        "option_c": "C) 3",
        "option_d": "D) ArithmeticException thrown at runtime",
        "correct_option": "C",
        "concept_explanation": "A return statement inside a finally block always executes and overrides prior returns or uncaught exceptions."
    },
    {
        "question_num": 17,
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "question": "In Java's HashMap implementation, what structural transition occurs when a bucket index has more than 8 nodes (TREEIFY_THRESHOLD) and total table capacity ≥ 64?",
        "option_a": "A) The bucket is converted from a linked list to an AVL Tree.",
        "option_b": "B) The bucket is converted from a linked list to a Red-Black Tree.",
        "option_c": "C) A Rehashing collision occurs and throws a ConcurrentModificationException.",
        "option_d": "D) The entries are migrated to a B-Tree structure.",
        "correct_option": "B",
        "concept_explanation": "Java 8+ converts high-collision linked buckets into balanced Red-Black Trees (TreeNode, O(log n) lookup)."
    },
    {
        "question_num": 18,
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "question": "Which functional interface from java.util.function takes two arguments of types T and U and returns an object of type R?",
        "option_a": "A) BiPredicate<T, U>",
        "option_b": "B) BiConsumer<T, U>",
        "option_c": "C) BiFunction<T, U, R>",
        "option_d": "D) BinaryOperator<T>",
        "correct_option": "C",
        "concept_explanation": "BiFunction<T, U, R> specifies SAM method R apply(T t, U u)."
    },
    {
        "question_num": 19,
        "subject": "Java",
        "sub_topic": "syntax_and_collections",
        "category": "procedural",
        "question": "What will the following Java Stream pipeline print?\n\nList<Integer> numbers = List.of(1, 2, 3, 4, 5);\nint result = numbers.stream()\n  .filter(n -> n % 2 != 0)\n  .map(n -> n * n)\n  .reduce(0, Integer::sum);\nSystem.out.println(result);",
        "option_a": "A) 35",
        "option_b": "B) 55",
        "option_c": "C) 20",
        "option_d": "D) 15",
        "correct_option": "A",
        "concept_explanation": "Odd elements: 1, 3, 5; squared: 1, 9, 25; sum = 1 + 9 + 25 = 35."
    },
    {
        "question_num": 20,
        "subject": "Java",
        "sub_topic": "oop_and_jvm_concepts",
        "category": "conceptual",
        "question": "Why is double-checked locking with a singleton instance broken in Java versions prior to Java 5?",
        "option_a": "A) ClassLoaders could load multiple copies of singleton classes concurrently.",
        "option_b": "B) Instruction reordering permitted the reference to be assigned to memory before the constructor finished execution.",
        "option_c": "C) The synchronized keyword was not supported on static methods.",
        "option_d": "D) Java garbage collector eagerly reclaimed singleton instances held in static fields.",
        "correct_option": "B",
        "concept_explanation": "Pre-JMM (pre-Java 5) instruction reordering allowed partially constructed instances to be observed."
    },

    # =========================================================================
    # SECTION 3: PYTHON PROGRAMMING (Questions 21-30)
    # =========================================================================
    {
        "question_num": 21,
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "question": "What is the fundamental difference between a Python list and a Python tuple?",
        "option_a": "A) Lists are immutable and ordered; tuples are mutable and unordered.",
        "option_b": "B) Lists are mutable and have dynamic resizing overhead; tuples are immutable and can be used as dictionary keys if all elements are hashable.",
        "option_c": "C) Lists only store homogeneous types, whereas tuples can store heterogeneous types.",
        "option_d": "D) Tuples do not support slicing or indexing operations.",
        "correct_option": "B",
        "concept_explanation": "Lists are mutable; tuples are immutable, memory-compact, and hashable if items are hashable."
    },
    {
        "question_num": 22,
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "question": "What is the output of the following Python program?\n\ndef extend_list(val, list_arg=[]):\n  list_arg.append(val)\n  return list_arg\n\nlist1 = extend_list(10)\nlist2 = extend_list(123, [])\nlist3 = extend_list('a')\nprint(list1, list2, list3)",
        "option_a": "A) [10] [123] ['a']",
        "option_b": "B) [10, 'a'] [123] [10, 'a']",
        "option_c": "C) [10] [123] [10, 'a']",
        "option_d": "D) [10, 123, 'a'] [123] [10, 123, 'a']",
        "correct_option": "B",
        "concept_explanation": "Default mutable arguments are bound at function definition time; list1 and list3 share the same object."
    },
    {
        "question_num": 23,
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "question": "What role does the Global Interpreter Lock (GIL) play in the standard CPython implementation?",
        "option_a": "A) It prevents deadlocks by synchronizing file I/O operations across distinct OS processes.",
        "option_b": "B) It ensures that only one native OS thread executes Python bytecode at any given moment, simplifying thread-safe memory management.",
        "option_c": "C) It automatically converts single-threaded code into multi-threaded parallel execution.",
        "option_d": "D) It restricts execution of untrusted binary extensions within sandbox containers.",
        "correct_option": "B",
        "concept_explanation": "CPython GIL serializes execution of Python bytecode across threads to safeguard memory management."
    },
    {
        "question_num": 24,
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "question": "What will be the output of the following dictionary comprehension snippet?\n\nkeys = ['a', 'b', 'c']\nvalues = [1, 2, 3]\nd = {k: v * 2 for k, v in zip(keys, values) if v % 2 != 0}\nprint(d)",
        "option_a": "A) {'a': 2, 'b': 4, 'c': 6}",
        "option_b": "B) {'b': 4}",
        "option_c": "C) {'a': 2, 'c': 6}",
        "option_d": "D) {1: 'a', 3: 'c'}",
        "correct_option": "C",
        "concept_explanation": "Pairs: ('a', 1), ('b', 2), ('c', 3). Odd values: 1 → 'a': 2 and 3 → 'c': 6."
    },
    {
        "question_num": 25,
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "question": "Consider the following generator function:\n\ndef counter():\n  x = 1\n  while x <= 3:\n    yield x\n    x += 1\n\ngen = counter()\nprint(next(gen), next(gen), list(gen))\n\nWhat is the output?",
        "option_a": "A) 1 2 [3]",
        "option_b": "B) 1 2 [1, 2, 3]",
        "option_c": "C) 1 2 []",
        "option_d": "D) 1 2 [2, 3]",
        "correct_option": "A",
        "concept_explanation": "next(gen) yields 1, next(gen) yields 2, list(gen) exhausts the remaining items: [3]."
    },
    {
        "question_num": 26,
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "question": "In Python's Method Resolution Order (MRO) using the C3 Linearization algorithm, what is the output of inspecting D.__mro__ given the inheritance below?\n\nclass A: pass\nclass B(A): pass\nclass C(A): pass\nclass D(B, C): pass",
        "option_a": "A) D → B → A → C → object",
        "option_b": "B) D → B → C → A → object",
        "option_c": "C) D → A → B → C → object",
        "option_d": "D) D → C → B → A → object",
        "correct_option": "B",
        "concept_explanation": "C3 linearization in diamond inheritance traverses branches before common base: D → B → C → A → object."
    },
    {
        "question_num": 27,
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "question": "What does the __slots__ declaration in a Python class definition accomplish?",
        "option_a": "A) Automatically creates getter and setter methods for declared attributes.",
        "option_b": "B) Prevents creation of the default dynamic instance dictionary __dict__, substantially reducing per-instance memory overhead.",
        "option_c": "C) Restricts method overriding by derived classes.",
        "option_d": "D) Makes all listed attributes private and unreadable from outside the class.",
        "correct_option": "B",
        "concept_explanation": "__slots__ suppresses per-instance __dict__, allocating fixed array-like slots for attributes."
    },
    {
        "question_num": 28,
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "question": "What does the following recursive function compute for input f(4, 3)?\n\ndef f(n, r):\n  if r == 0 or n == r:\n    return 1\n  return f(n - 1, r - 1) + f(n - 1, r)",
        "option_a": "A) 4",
        "option_b": "B) 6",
        "option_c": "C) 12",
        "option_d": "D) 24",
        "correct_option": "A",
        "concept_explanation": "Computes combination C(n, r) via Pascal's identity. C(4, 3) = 4! / (3! × 1!) = 4."
    },
    {
        "question_num": 29,
        "subject": "Python",
        "sub_topic": "oop_and_design_patterns",
        "category": "conceptual",
        "question": "Which built-in function or decorator is required when defining a context manager using a generator function in Python?",
        "option_a": "A) @functools.wraps",
        "option_b": "B) @contextlib.contextmanager",
        "option_c": "C) @dataclass",
        "option_d": "D) @property",
        "correct_option": "B",
        "concept_explanation": "@contextlib.contextmanager converts generator functions yielding once into context managers."
    },
    {
        "question_num": 30,
        "subject": "Python",
        "sub_topic": "syntax_and_core_libraries",
        "category": "procedural",
        "question": "What will be the output of the following slice assignment?\n\nnums = [1, 2, 3, 4, 5]\nnums[1:4] = [20, 30]\nprint(nums)",
        "option_a": "A) [1, 20, 30, 4, 5]",
        "option_b": "B) [1, 20, 30, 5]",
        "option_c": "C) [1, [20, 30], 5]",
        "option_d": "D) ValueError: cannot assign sequence of size 2 to extended slice of size 3",
        "correct_option": "B",
        "concept_explanation": "Slice assignment replaces elements at index 1, 2, 3 ([2, 3, 4]) with [20, 30], resulting in [1, 20, 30, 5]."
    },

    # =========================================================================
    # SECTION 4: MACHINE LEARNING (Questions 31-40)
    # =========================================================================
    {
        "question_num": 31,
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "question": "A binary classification model yields a Confusion Matrix with: True Positives (TP) = 80, False Positives (FP) = 20, True Negatives (TN) = 90, and False Negatives (FN) = 10. What is the Precision of the model?",
        "option_a": "A) 0.80",
        "option_b": "B) 0.889",
        "option_c": "C) 0.85",
        "option_d": "D) 0.82",
        "correct_option": "A",
        "concept_explanation": "Precision = TP / (TP + FP) = 80 / (80 + 20) = 80 / 100 = 0.80."
    },
    {
        "question_num": 32,
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "question": "What is the key functional difference between L1 Regularization (Lasso) and L2 Regularization (Ridge) in linear models?",
        "option_a": "A) L2 drives non-informative feature weights strictly to zero, producing sparse models; L1 only shrinks weights toward zero.",
        "option_b": "B) L1 adds a penalty proportional to the absolute value of coefficients, leading to sparse feature selection; L2 adds a squared penalty, shrinking weights smoothly.",
        "option_c": "C) L1 can only be applied to classification problems, while L2 is reserved for regression.",
        "option_d": "D) L1 assumes Gaussian priors on weights, while L2 assumes Laplacian priors on weights.",
        "correct_option": "B",
        "concept_explanation": "L1 norm penalty has non-differentiable corners at zero, yielding sparse parameter vectors."
    },
    {
        "question_num": 33,
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "question": "In the context of the Bias-Variance tradeoff, what symptom characterizes a model suffering from high variance?",
        "option_a": "A) High training error and high testing error (underfitting).",
        "option_b": "B) Low training error paired with significantly higher testing error (overfitting).",
        "option_c": "C) Constant predictions regardless of input features.",
        "option_d": "D) Strong insensitivity to small fluctuations in training datasets.",
        "correct_option": "B",
        "concept_explanation": "High variance implies overfitting: sensitive to training noise, failing to generalize to unseen data."
    },
    {
        "question_num": 34,
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "question": "How does the vanishing gradient problem primarily arise during backpropagation in deep neural networks when using standard Sigmoid activation functions?",
        "option_a": "A) The derivative of the sigmoid function peaks at 0.25; chaining multiple derivatives less than 1.0 causes upstream gradients to exponentially decay toward zero.",
        "option_b": "B) The learning rate dynamically decreases to zero during early training epochs.",
        "option_c": "C) Sigmoid activations cause matrix inversion singularity in weight initialization.",
        "option_d": "D) The weights explode because the derivative exceeds 1.0 at large positive inputs.",
        "correct_option": "A",
        "concept_explanation": "Sigmoid derivative σ'(z) ≤ 0.25; product of multiple small terms causes gradients to vanish."
    },
    {
        "question_num": 35,
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "question": "Which of the following statements accurately contrasts Bagging (e.g., Random Forest) and Boosting (e.g., AdaBoost, XGBoost)?",
        "option_a": "A) Bagging builds weak learners sequentially to reduce bias; Boosting trains base models in parallel to reduce variance.",
        "option_b": "B) Bagging trains diverse base models in parallel on bootstrap samples to reduce variance; Boosting trains models sequentially, assigning higher weight to previous errors to reduce bias.",
        "option_c": "C) Random Forests always overfit faster than AdaBoost on noisy data.",
        "option_d": "D) Boosting uses sub-sampling with replacement, whereas Bagging never repeats training instances.",
        "correct_option": "B",
        "concept_explanation": "Bagging reduces variance via parallel bootstrap aggregation; Boosting reduces bias via sequential re-weighting."
    },
    {
        "question_num": 36,
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "question": "In K-Means clustering, what does the 'Elbow Method' inspect to evaluate the optimal number of clusters k?",
        "option_a": "A) The point where the Within-Cluster Sum of Squares (WCSS / Inertia) exhibits an inflection where marginal decreases diminish sharply.",
        "option_b": "B) The point where between-cluster variance equals zero.",
        "option_c": "C) The maximum value of the Akaike Information Criterion (AIC).",
        "option_d": "D) The point where the number of clusters equals the number of features.",
        "correct_option": "A",
        "concept_explanation": "The elbow bend marks the point of diminishing returns in WCSS reduction as k increases."
    },
    {
        "question_num": 37,
        "subject": "Machine Learning",
        "sub_topic": "algorithms_and_theory",
        "category": "conceptual",
        "question": "What is the fundamental role of the Support Vectors in a Support Vector Machine (SVM)?",
        "option_a": "A) They represent data points lying farthest from the decision boundary that do not influence margin calculation.",
        "option_b": "B) They are the critical data points lying closest to the decision hyperplane that define the margin boundaries and the separating plane itself.",
        "option_c": "C) They are synthetic data instances generated via kernel trick interpolation.",
        "option_d": "D) They correspond to the cluster centroids identified during PCA preprocessing.",
        "correct_option": "B",
        "concept_explanation": "Support vectors lie on margin boundaries; non-support vectors can be removed without altering the hyperplane."
    },
    {
        "question_num": 38,
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "question": "In Principal Component Analysis (PCA), what mathematical objects represent the principal axes of maximal variance and the magnitude of variance explained along those axes, respectively?",
        "option_a": "A) The eigenvalues represent the principal axes; eigenvectors represent the variance explained.",
        "option_b": "B) The eigenvectors of the data covariance matrix represent the principal directions; their corresponding eigenvalues quantify the variance explained.",
        "option_c": "C) The inverse diagonal of the correlation matrix represents the principal components.",
        "option_d": "D) The determinant represents the axis orientation; trace represents total components.",
        "correct_option": "B",
        "concept_explanation": "Eigenvectors form the orthogonal projection matrix; eigenvalues measure the variance along each eigenvector."
    },
    {
        "question_num": 39,
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "question": "In a Convolutional Neural Network (CNN), an input image of size 32 × 32 × 3 is convolved with 10 filters of size 5 × 5, with stride 1 and padding 0. What is the spatial dimension of the resulting feature map?",
        "option_a": "A) 28 × 28 × 10",
        "option_b": "B) 28 × 28 × 3",
        "option_c": "C) 32 × 32 × 10",
        "option_d": "D) 27 × 27 × 10",
        "correct_option": "A",
        "concept_explanation": "Output dimension = ((W - K + 2P)/S) + 1 = ((32 - 5 + 0)/1) + 1 = 28; depth equals number of filters = 10."
    },
    {
        "question_num": 40,
        "subject": "Machine Learning",
        "sub_topic": "model_apis_and_libraries",
        "category": "procedural",
        "question": "Which sampling technique is specifically designed to handle severe class imbalance by generating synthetic examples of the minority class using nearest neighbors?",
        "option_a": "A) Stratified K-Fold",
        "option_b": "B) SMOTE (Synthetic Minority Over-sampling Technique)",
        "option_c": "C) Random Undersampling",
        "option_d": "D) ElasticNet Regularization",
        "correct_option": "B",
        "concept_explanation": "SMOTE interpolates synthetic feature vectors along line segments connecting k-nearest minority neighbors."
    },

    # =========================================================================
    # SECTION 5: DATA STRUCTURES & ALGORITHMS (DSA) (Questions 41-50)
    # =========================================================================
    {
        "question_num": 41,
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "question": "What is the worst-case time complexity of searching for an element in a binary search tree (BST) containing n nodes?",
        "option_a": "A) O(1)",
        "option_b": "B) O(log n)",
        "option_c": "C) O(n)",
        "option_d": "D) O(n log n)",
        "correct_option": "C",
        "concept_explanation": "In an unbalanced/skewed BST, height degrades to n, resulting in O(n) search time."
    },
    {
        "question_num": 42,
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "question": "What is the minimum number of queues required to implement a standard Last-In-First-Out (LIFO) Stack?",
        "option_a": "A) 1",
        "option_b": "B) 2",
        "option_c": "C) 3",
        "option_d": "D) Cannot be implemented using queues",
        "correct_option": "A",
        "concept_explanation": "A stack can be implemented using a single queue by rotating elements of size n-1 after each push."
    },
    {
        "question_num": 43,
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "question": "Consider an array of size n. Which of the following sorting algorithms is in-place and maintains stability by default?",
        "option_a": "A) Quick Sort (Lomuto partition)",
        "option_b": "B) Heap Sort",
        "option_c": "C) Insertion Sort",
        "option_d": "D) Selection Sort",
        "correct_option": "C",
        "concept_explanation": "Insertion Sort runs in-place (O(1) auxiliary memory) and does not swap identical keys across distances."
    },
    {
        "question_num": 44,
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "question": "What is the time complexity of building a Binary Max-Heap from an unsorted array of n integers using the bottom-up buildHeap method?",
        "option_a": "A) O(n)",
        "option_b": "B) O(n log n)",
        "option_c": "C) O(log n)",
        "option_d": "D) O(n²)",
        "correct_option": "A",
        "concept_explanation": "Bottom-up heap construction sums node depths in geometric progression, converging strictly to O(n)."
    },
    {
        "question_num": 45,
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "question": "In Floyd's Cycle Detection Algorithm (Tortoise and Hare), if the slow pointer moves 1 step and the fast pointer moves 2 steps, what is the upper-bound time complexity for detecting whether a singly linked list with n nodes contains a cycle?",
        "option_a": "A) O(log n)",
        "option_b": "B) O(n)",
        "option_c": "C) O(n²)",
        "option_d": "D) O(1)",
        "correct_option": "B",
        "concept_explanation": "The distance between slow and fast pointers decreases by 1 in each cycle step, guaranteeing convergence in O(n)."
    },
    {
        "question_num": 46,
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "question": "Dijkstra's shortest-path algorithm fails or yields incorrect shortest paths under which of the following graph conditions?",
        "option_a": "A) Graphs with cycles of positive weights",
        "option_b": "B) Directed acyclic graphs",
        "option_c": "C) Graphs containing negative weight edges",
        "option_d": "D) Disconnected graph components",
        "correct_option": "C",
        "concept_explanation": "Dijkstra's greedy choice assumes adding edges never decreases path costs; negative edges break this invariant."
    },
    {
        "question_num": 47,
        "subject": "DSA",
        "sub_topic": "complexity_and_problem_solving",
        "category": "conceptual",
        "question": "What is the recurrence relation and time complexity for solving the 0/1 Knapsack Problem with N items and knapsack capacity W using 2D dynamic programming?",
        "option_a": "A) T(n) = 2T(n/2) + O(1), giving O(n)",
        "option_b": "B) Recurrence over items and capacity yielding pseudo-polynomial time complexity O(N × W)",
        "option_c": "C) O(N log W) using binary lifting",
        "option_d": "D) Strictly strongly polynomial time O(N²) regardless of capacity W",
        "correct_option": "B",
        "concept_explanation": "0/1 Knapsack DP fills an N × W table, which is pseudo-polynomial in input magnitude W."
    },
    {
        "question_num": 48,
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "question": "In an AVL Tree, after inserting a node into the left subtree of the right child of an unbalanced node, which rotation sequence restores balance?",
        "option_a": "A) Left-Left (Single Right Rotation)",
        "option_b": "B) Right-Right (Single Left Rotation)",
        "option_c": "C) Right-Left (RL Rotation: Right rotation on child, then Left rotation on node)",
        "option_d": "D) Left-Right (LR Rotation: Left rotation on child, then Right rotation on node)",
        "correct_option": "C",
        "concept_explanation": "A Right-Left (RL) imbalance requires a right rotation on the right child followed by a left rotation on the parent."
    },
    {
        "question_num": 49,
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "question": "What is the amortized time complexity of the union and find operations in a Disjoint Set Union (DSU) structure that employs both path compression and union by rank?",
        "option_a": "A) O(log n)",
        "option_b": "B) O(1)",
        "option_c": "C) O(α(n)), where α is the Inverse Ackermann function",
        "option_d": "D) O(n)",
        "correct_option": "C",
        "concept_explanation": "Combined path compression and union by rank yields amortized O(α(n)) time per operation."
    },
    {
        "question_num": 50,
        "subject": "DSA",
        "sub_topic": "implementation_and_syntax",
        "category": "procedural",
        "question": "Given the prefix expression - + * 2 3 4 5, what is its evaluated numerical result?",
        "option_a": "A) 5",
        "option_b": "B) 9",
        "option_c": "C) 1",
        "option_d": "D) 15",
        "correct_option": "A",
        "concept_explanation": "Prefix evaluation from right: (* 2 3) = 6 → (+ 6 4) = 10 → (- 10 5) = 5."
    }
]
