import React, { useState, useEffect, useCallback } from "react";
import { api } from "../api/client";

const SKILL_META = {
  Python:             { color: "#4f8ef7", bg: "#eff6ff", icon: "🐍", accentBg: "#dbeafe" },
  Java:               { color: "#f59e0b", bg: "#fffbeb", icon: "☕", accentBg: "#fef3c7" },
  DBMS:               { color: "#6366f1", bg: "#eef2ff", icon: "🗄️", accentBg: "#e0e7ff" },
  "Machine Learning": { color: "#8b5cf6", bg: "#f5f3ff", icon: "🧠", accentBg: "#ede9fe" },
  DSA:                { color: "#ef4444", bg: "#fef2f2", icon: "⚡", accentBg: "#fee2e2" },
};

const RECOMMENDATIONS = [
  {
    subject: "DSA",
    subTopicKey: "complexity_and_problem_solving",
    label: "Complexity & Problem Solving",
    decay: 81,
    urgency: "Critical",
    urgClass: "rec-urg-crit",
    reason: "Highest decay detected — immediate review recommended by signal engine.",
    estimatedTime: "45 min",
    questionCount: 10,
  },
  {
    subject: "Machine Learning",
    subTopicKey: "algorithms_and_theory",
    label: "Algorithms & Theory",
    decay: 73,
    urgency: "High",
    urgClass: "rec-urg-high",
    reason: "Significant retention drop since last session. BKT confidence dropping.",
    estimatedTime: "35 min",
    questionCount: 10,
  },
  {
    subject: "Python",
    subTopicKey: "oop_and_design_patterns",
    label: "OOP & Design Patterns",
    decay: 68,
    urgency: "High",
    urgClass: "rec-urg-high",
    reason: "Knowledge curve shows steep decline. Reinforce core OOP concepts.",
    estimatedTime: "30 min",
    questionCount: 10,
  },
  {
    subject: "Java",
    subTopicKey: "oop_and_jvm_concepts",
    label: "OOP & JVM Concepts",
    decay: 52,
    urgency: "Medium",
    urgClass: "rec-urg-med",
    reason: "Moderate decay risk. Scheduled for proactive reinforcement.",
    estimatedTime: "25 min",
    questionCount: 10,
  },
  {
    subject: "DBMS",
    subTopicKey: "sql_queries_and_joins",
    label: "SQL Queries & Joins",
    decay: 47,
    urgency: "Medium",
    urgClass: "rec-urg-med",
    reason: "Retention stable but approaching the 50% decay threshold.",
    estimatedTime: "25 min",
    questionCount: 10,
  },
];

const URGENCY_ORDER = { Critical: 0, High: 1, Medium: 2, Low: 3 };

export default function RecommendationsPage({ onTestNowClick, loading }) {
  const [skillsData, setSkillsData] = useState(null);
  const [activeFilter, setActiveFilter] = useState("all");

  const fetchSkills = useCallback(async () => {
    try {
      const data = await api.getSkills();
      setSkillsData(data);
    } catch (e) {
      console.error("Failed to fetch skills", e);
    }
  }, []);

  useEffect(() => {
    fetchSkills();
  }, [fetchSkills]);

  const filtered = RECOMMENDATIONS.filter((r) => {
    if (activeFilter === "all") return true;
    return r.urgency.toLowerCase() === activeFilter;
  }).sort((a, b) => URGENCY_ORDER[a.urgency] - URGENCY_ORDER[b.urgency]);

  const critCount = RECOMMENDATIONS.filter((r) => r.urgency === "Critical").length;
  const highCount = RECOMMENDATIONS.filter((r) => r.urgency === "High").length;
  const medCount = RECOMMENDATIONS.filter((r) => r.urgency === "Medium").length;

  return (
    <div className="rp-root">
      {/* Page header */}
      <div className="rp-page-head">
        <div className="rp-head-left">
          <div className="rp-head-badge">
            <span className="rp-pulse-dot" />
            SDA Signal Engine · Live
          </div>
          <h1 className="rp-page-title">Study Recommendations</h1>
          <p className="rp-page-sub">
            Personalized test recommendations generated by your Bayesian Knowledge Tracing model and decay analysis engine.
          </p>
        </div>
        <div className="rp-head-stats">
          <div className="rp-head-stat">
            <span className="rp-head-stat-val" style={{ color: "#ef4444" }}>{critCount}</span>
            <span className="rp-head-stat-lbl">Critical</span>
          </div>
          <div className="rp-head-stat-divider" />
          <div className="rp-head-stat">
            <span className="rp-head-stat-val" style={{ color: "#f59e0b" }}>{highCount}</span>
            <span className="rp-head-stat-lbl">High</span>
          </div>
          <div className="rp-head-stat-divider" />
          <div className="rp-head-stat">
            <span className="rp-head-stat-val" style={{ color: "#6366f1" }}>{medCount}</span>
            <span className="rp-head-stat-lbl">Medium</span>
          </div>
        </div>
      </div>

      {/* How it works card */}
      <div className="rp-info-card">
        <div className="rp-info-icon">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="12" cy="12" r="3"/><path d="M19.07 4.93a10 10 0 010 14.14M4.93 4.93a10 10 0 000 14.14"/>
            <path d="M22 12a10 10 0 00-10-10M2 12a10 10 0 0010 10"/>
          </svg>
        </div>
        <div className="rp-info-body">
          <div className="rp-info-title">How recommendations are generated</div>
          <div className="rp-info-text">
            The SDA Signal Engine continuously monitors your retention curves using <strong>pyBKT Bayesian Knowledge Tracing</strong>. 
            When a skill's decay score crosses a threshold, the <strong>Featherless Decision Agent</strong> classifies urgency and queues a targeted test. 
            Complete tests to update your mastery model in real-time.
          </div>
        </div>
      </div>

      {/* Filter bar */}
      <div className="rp-filter-row">
        <div className="rp-filter-bar">
          {[
            { key: "all", label: `All (${RECOMMENDATIONS.length})` },
            { key: "critical", label: `🔴 Critical (${critCount})` },
            { key: "high", label: `🟠 High (${highCount})` },
            { key: "medium", label: `🔵 Medium (${medCount})` },
          ].map(({ key, label }) => (
            <button
              key={key}
              className={`rp-filter-chip ${activeFilter === key ? "active" : ""}`}
              onClick={() => setActiveFilter(key)}
            >
              {label}
            </button>
          ))}
        </div>
        <div className="rp-showing-count">{filtered.length} recommendation{filtered.length !== 1 ? "s" : ""}</div>
      </div>

      {/* Recommendations list */}
      <div className="rp-rec-list">
        {filtered.map((rec, idx) => {
          const meta = SKILL_META[rec.subject] || { color: "#64748b", bg: "#f8fafc", icon: "💻", accentBg: "#f1f5f9" };
          const retention = 100 - rec.decay;
          const retColor = retention < 30 ? "#ef4444" : retention < 50 ? "#f59e0b" : "#10b981";

          return (
            <div className="rp-rec-card" key={rec.subject} style={{ "--card-color": meta.color }}>
              {/* Left accent bar */}
              <div className="rp-rec-accent" style={{ background: meta.color }} />

              {/* Card content */}
              <div className="rp-rec-content">
                {/* Top row */}
                <div className="rp-rec-top">
                  <div className="rp-rec-identity">
                    <span className="rp-rec-icon-badge" style={{ background: meta.bg, color: meta.color }}>
                      {meta.icon}
                    </span>
                    <div>
                      <div className="rp-rec-subject">{rec.subject}</div>
                      <div className="rp-rec-topic">{rec.label}</div>
                    </div>
                  </div>
                  <div className="rp-rec-right">
                    <span className={`rp-urgency-chip ${rec.urgClass}`}>{rec.urgency}</span>
                    <span className="rp-rec-rank">#{idx + 1}</span>
                  </div>
                </div>

                {/* Reason row */}
                <div className="rp-rec-reason">
                  <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                    <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
                  </svg>
                  {rec.reason}
                </div>

                {/* Stats + retention bar + CTA */}
                <div className="rp-rec-bottom">
                  <div className="rp-rec-metrics">
                    <div className="rp-metric">
                      <div className="rp-metric-val">{retention}%</div>
                      <div className="rp-metric-lbl">Retention</div>
                    </div>
                    <div className="rp-metric">
                      <div className="rp-metric-val">{rec.decay}%</div>
                      <div className="rp-metric-lbl">Decay Score</div>
                    </div>
                    <div className="rp-metric">
                      <div className="rp-metric-val">{rec.questionCount}Q</div>
                      <div className="rp-metric-lbl">Questions</div>
                    </div>
                    <div className="rp-metric">
                      <div className="rp-metric-val">{rec.estimatedTime}</div>
                      <div className="rp-metric-lbl">Est. Time</div>
                    </div>
                  </div>

                  <div className="rp-rec-bar-cta">
                    <div className="rp-ret-bar-wrap">
                      <div className="rp-ret-bar-track">
                        <div
                          className="rp-ret-bar-fill"
                          style={{ width: `${retention}%`, background: retColor }}
                        />
                      </div>
                      <span className="rp-ret-bar-label" style={{ color: retColor }}>
                        {retention < 30 ? "Critical" : retention < 50 ? "At Risk" : "Moderate"}
                      </span>
                    </div>
                    <button
                      className="rp-btn-start"
                      style={{ "--btn-accent": meta.color }}
                      onClick={() => onTestNowClick(rec.subject, rec.subTopicKey)}
                      disabled={loading}
                    >
                      <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                        <polygon points="5 3 19 12 5 21 5 3"/>
                      </svg>
                      Start Test
                    </button>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Bottom tip */}
      <div className="rp-bottom-tip">
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#6366f1" strokeWidth="2" strokeLinecap="round">
          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
        </svg>
        Completing tests updates your pyBKT mastery estimate and re-ranks recommendations in real-time.
      </div>
    </div>
  );
}
